x = 10
y = 3
print(" {0} + {1} => {2}".format(x,y , x + y))
print(" {0} - {1} => {2}".format(x,y , x-y))
print(" {0} * {1} => {2}".format(x,y , x*y))
print(" {0} / {1} => {2}".format(x,y , x/y))
print(" {0} % {1} => {2}".format(x,y , x%y))
print(" {0} // {1} => {2}".format(x,y , x//y))
print(" {0} ** {1} => {2}".format(x,y , x**y))