print("True AND False", True and False)
print("True AND True", True and True)
print("True or False", True or False)
print("True or True", True or True)
print("not True", not True)
print("not False", not False)

print("0 and True", 0 and True)
print("0 or True", 0 or True)
print("'Hello' or True", 'Hello' or True)